name: test

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['10', '12', '14', '16']

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install and build
        run: npm install && npm run build

      - name: Run test
        run: npm test
